const fs = require("fs");
const path = require("path");

const srcDir = path.join(__dirname, "src");

function walkDir(dir, callback) {
  fs.readdirSync(dir).forEach((f) => {
    let dirPath = path.join(dir, f);
    let isDirectory = fs.statSync(dirPath).isDirectory();
    isDirectory ? walkDir(dirPath, callback) : callback(path.join(dir, f));
  });
}

function processFile(filePath) {
  if (!filePath.endsWith(".tsx") && !filePath.endsWith(".ts")) return;

  let content = fs.readFileSync(filePath, "utf8");
  let original = content;

  // 1. Remove glowing text and box shadows
  content = content.replace(
    /shadow-violet-\d+(?:\/\d+)?/g,
    "shadow-sm shadow-black/5 dark:shadow-black/20",
  );
  content = content.replace(
    /shadow-lg shadow-black\/10 dark:shadow-black\/40/g,
    "shadow-sm shadow-black/5 dark:shadow-none",
  );
  content = content.replace(
    /shadow-xl shadow-black\/20 dark:shadow-\[0_8px_32px_rgba\(0,0,0,0\.7\)\]/g,
    "shadow-md shadow-black/5 dark:shadow-none border dark:border-zinc-800",
  );
  content = content.replace(
    /hover:shadow-xl hover:shadow-violet-100 dark:hover:shadow-black\/50/g,
    "hover:shadow-md hover:shadow-black/5 dark:hover:shadow-none",
  );
  content = content.replace(
    /shadow-md shadow-violet-500\/30/g,
    "shadow-sm shadow-black/10",
  );
  content = content.replace(/drop-shadow-\[.*?\]/g, "");

  // 2. Remove animations
  content = content.replace(/animate-\[float.*?\]/g, "");

  // 3. Flatten dark mode backgrounds to standard zinc instead of deep purple-blacks
  content = content.replace(/dark:bg-\[#0b0510\]/g, "dark:bg-zinc-950");
  content = content.replace(/dark:bg-\[#12091c\]/g, "dark:bg-zinc-950");
  content = content.replace(/dark:bg-\[#0e0715\]/g, "dark:bg-zinc-900");
  content = content.replace(/dark:bg-\[#140a20\]/g, "dark:bg-zinc-800");

  // Also simplify some violet backgrounds that might be too much in dark mode
  content = content.replace(/dark:bg-violet-950\/20/g, "dark:bg-zinc-900");
  content = content.replace(/dark:bg-violet-950/g, "dark:bg-zinc-900");
  content = content.replace(/dark:bg-violet-900\/20/g, "dark:bg-zinc-900");
  content = content.replace(/dark:bg-violet-900\/30/g, "dark:bg-zinc-800");
  content = content.replace(/dark:bg-violet-900\/40/g, "dark:bg-zinc-800");
  content = content.replace(/dark:bg-violet-900\/50/g, "dark:bg-zinc-800");

  // Update hover backgrounds
  content = content.replace(
    /dark:hover:bg-violet-900\/20/g,
    "dark:hover:bg-zinc-800",
  );

  // 4. Simplify borders in dark mode
  content = content.replace(
    /dark:border-violet-900\/50/g,
    "dark:border-zinc-800",
  );
  content = content.replace(
    /dark:border-violet-800\/50/g,
    "dark:border-zinc-800",
  );
  content = content.replace(
    /dark:border-violet-800\/60/g,
    "dark:border-zinc-800",
  );
  content = content.replace(
    /dark:border-violet-800\/70/g,
    "dark:border-zinc-800",
  );
  content = content.replace(
    /dark:border-violet-800\/40/g,
    "dark:border-zinc-800",
  );
  content = content.replace(
    /dark:border-violet-900\/30/g,
    "dark:border-zinc-800",
  );
  content = content.replace(/dark:border-violet-900/g, "dark:border-zinc-800");
  content = content.replace(/dark:border-violet-800/g, "dark:border-zinc-800");

  content = content.replace(
    /dark:hover:border-violet-600\/80/g,
    "dark:hover:border-zinc-700",
  );
  content = content.replace(
    /dark:hover:border-violet-600/g,
    "dark:hover:border-zinc-700",
  );
  content = content.replace(
    /hover:border-violet-500/g,
    "hover:border-slate-300",
  );

  // 5. Remove gradients
  content = content.replace(
    /bg-gradient-to-b from-violet-100 to-slate-50/g,
    "bg-white",
  );
  content = content.replace(
    /dark:from-violet-950 dark:to-\[#0b0510\]/g,
    "dark:bg-zinc-950",
  );

  // 6. Ring/Focus logic
  content = content.replace(
    /focus-visible:ring-violet-500\/40/g,
    "focus-visible:ring-violet-500/20",
  );

  // Clean up any double spaces generated by regex replacements
  content = content.replace(/\s{2,}/g, (match) => {
    // only apply if it's within a className string - rough heuristic
    return match.includes("\n") ? match : " ";
  });

  if (content !== original) {
    fs.writeFileSync(filePath, content, "utf8");
    console.log(`Updated ${filePath}`);
  }
}

walkDir(srcDir, processFile);
console.log("Minimalist style refactor complete.");
